parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Util\Common\EnvParamsReceiver:
        bind:
            $daysSequenceBefore: '%env(DAYS_BEFORE)%'
            $daysSequenceAfter: '%env(DAYS_AFTER)%'
            $notifyInDateExpiration: '%env(NOTIFY_IN_DATE_EXPIRATION)%'
            $communicationModuleForCsvSendingUri: '%env(COMMUNICATION_MODULE_FOR_CSV_SENDING_URI)%'
            $communicationModuleToken: '%env(COMMUNICATION_MODULE_TOKEN)%'